export type Region = 'Northeast' | 'Midwest' | 'South' | 'West';

const STATE_TO_REGION: Record<string, Region> = {
  CT: 'Northeast',
  ME: 'Northeast',
  MA: 'Northeast',
  NH: 'Northeast',
  RI: 'Northeast',
  VT: 'Northeast',
  NJ: 'Northeast',
  NY: 'Northeast',
  PA: 'Northeast',
  IL: 'Midwest',
  IN: 'Midwest',
  IA: 'Midwest',
  KS: 'Midwest',
  MI: 'Midwest',
  MN: 'Midwest',
  MO: 'Midwest',
  NE: 'Midwest',
  ND: 'Midwest',
  OH: 'Midwest',
  SD: 'Midwest',
  WI: 'Midwest',
  AL: 'South',
  AR: 'South',
  DE: 'South',
  FL: 'South',
  GA: 'South',
  KY: 'South',
  LA: 'South',
  MD: 'South',
  MS: 'South',
  NC: 'South',
  OK: 'South',
  SC: 'South',
  TN: 'South',
  TX: 'South',
  VA: 'South',
  WV: 'South',
  DC: 'South',
  AK: 'West',
  AZ: 'West',
  CA: 'West',
  CO: 'West',
  HI: 'West',
  ID: 'West',
  MT: 'West',
  NM: 'West',
  NV: 'West',
  OR: 'West',
  UT: 'West',
  WA: 'West',
  WY: 'West',
};

export function stateToRegion(state?: string | null): Region | null {
  if (!state) return null;
  const key = state.trim().toUpperCase();
  const normalized = key.replace(/[\\s.,]/g, '');
  const abbreviation = STATE_NAME_TO_ABBREV[normalized] ?? key;
  return STATE_TO_REGION[abbreviation] ?? null;
}

export const REGION_OPTIONS: Region[] = [
  'Northeast',
  'Midwest',
  'South',
  'West',
];

const STATE_NAME_TO_ABBREV: Record<string, string> = {
  ALABAMA: 'AL',
  ALASKA: 'AK',
  ARIZONA: 'AZ',
  ARKANSAS: 'AR',
  CALIFORNIA: 'CA',
  COLORADO: 'CO',
  CONNECTICUT: 'CT',
  DELAWARE: 'DE',
  FLORIDA: 'FL',
  GEORGIA: 'GA',
  HAWAII: 'HI',
  IDAHO: 'ID',
  ILLINOIS: 'IL',
  INDIANA: 'IN',
  IOWA: 'IA',
  KANSAS: 'KS',
  KENTUCKY: 'KY',
  LOUISIANA: 'LA',
  MAINE: 'ME',
  MARYLAND: 'MD',
  MASSACHUSETTS: 'MA',
  MICHIGAN: 'MI',
  MINNESOTA: 'MN',
  MISSISSIPPI: 'MS',
  MISSOURI: 'MO',
  MONTANA: 'MT',
  NEBRASKA: 'NE',
  NEVADA: 'NV',
  NEWHAMPSHIRE: 'NH',
  NEWJERSEY: 'NJ',
  NEWMEXICO: 'NM',
  NEWYORK: 'NY',
  NORTHCAROLINA: 'NC',
  NORTHDAKOTA: 'ND',
  OHIO: 'OH',
  OKLAHOMA: 'OK',
  OREGON: 'OR',
  PENNSYLVANIA: 'PA',
  RHODEISLAND: 'RI',
  SOUTHCAROLINA: 'SC',
  SOUTHDAKOTA: 'SD',
  TENNESSEE: 'TN',
  TEXAS: 'TX',
  UTAH: 'UT',
  VERMONT: 'VT',
  VIRGINIA: 'VA',
  WASHINGTON: 'WA',
  WESTVIRGINIA: 'WV',
  WISCONSIN: 'WI',
  WYOMING: 'WY',
  DISTRICTOFCOLUMBIA: 'DC',
  WASHINGTONDC: 'DC',
};
